#!/usr/bin/env bash

## Colors
ClrBld=$(tput bold)
ClrDim=$(tput dim)
ClrRed=$(tput setaf 196)
ClrGrn=$(tput setaf 040)
ClrOff=$(tput sgr0)

## Greeting
printf '%s\n\n' \
	"${ClrGrn}${ClrBld}Local Speedtest${ClrOff}"

## Obtain local server's IP address(es)
printf '%s\n' \
	"${ClrDim}Obtaining all public IP details for this host...${ClrOff}"
PublicIP="$(curl -s 'ipinfo.io/ip'; echo)"

## If Tailscale is installed/running obtain info
if command -v tailscale >/dev/null 2>&1; then
	Tailscale=y
	TailscaleIP4=
	TailscaleIP6=
	while read -r Line; do
		if [[ $Line != *Warning* ]]; then
			IFS=$'\n' read -rd '' IP <<<"$Line"; unset IFS
			if [[ -z "${TailscaleIP4}" ]]; then
				TailscaleIP4="${IP%% *}"
			else
				TailscaleIP6="${IP%% *}"
			fi
		fi
	done < <(tailscale ip 2> /dev/null)
fi

## Check for iperf daemon; start if necessary
Kernel=$(uname)
if [[ $Kernel == Linux ]]; then
	if command -v ss >/dev/null 2>&1; then
		Cmd=ss
	elif command -v netstat >/dev/null 2>&1; then
		Cmd=netstat
	fi
	if $Cmd -l | grep :25002 >/dev/null 2>&1; then
		Daemon=y
	fi
elif [[ $Kernel == Darwin ]]; then
	if lsof -i -nP | grep :25002 >/dev/null 2>&1; then
		Daemon=y
	fi
else printf '%s\n' \
	"Unknown kernal '${Kernel}', continuing..."
fi

if [[ $Daemon != y ]]; then
	printf '%s\n' \
		"Starting local ${ClrBld}iperf${ClrOff} daemon..."

	## Locate newest iperf
	if command -v iperf3 >/dev/null 2>&1; then
		Cmd=iperf3
	elif command -v iperf2 >/dev/null 2>&1; then
		Cmd=iperf2
	elif command -v iperf >/dev/null 2>&1; then
		Cmd=iperf
	else printf '%s\n' \
		"${ClrRed}${ClrBld}Error: No local 'iperf' was found...${ClrOff}"
		exit 2
	fi
	[[ -n $Cmd ]] && $Cmd -D -i1 -s -p 25002
else
	printf '%s\n' \
		"Local ${ClrBld}iperf${ClrOff} daemon is running..."
fi

## Provide public IPv4 test commands
printf "\n%s\n\n" \
	"'iperf' is required on your remote client. Version 3 is recommended especially for UDP testing. To check your version(s), run the following command on your remote client:" \
	| fmt -w 80
printf '%s\n\n' \
	"${ClrGrn}${ClrBld}for i in iperf iperf2 iperf3; do [ \$(command -v \$i) ] && \$i -v | head -1; done${ClrOff}"

read -rp "  → What version of iperf is installed on your remote client? [2/3]: " iperfVersion
case "${iperfVersion}" in
	2 )	printf '\n%s\n' \
			"*** Continuing with ${ClrBld}iperf2${ClrOff} commands ***"
		Version=""
		;;
	3 )	printf '\n\n%s\n' \
			"*** Continuing with ${ClrBld}iperf3${ClrOff} commands ***"
		Version="3"
		;;
	* )	printf '\n%s\n' \
			"${ClrRed}*** ERROR: Invalid response; terminating ***${ClrOff}"
		exit 1
		;;
esac

printf '\n%s\n' \
	"Use the commands below on your remote client as a guide for testing."
printf '%s\n' \
	" - Add ${ClrGrn}${ClrBld}-R${ClrOff} to the end of a command to Reverse the traffic flow."
printf '%s\n\n' \
	" - UDP commands are set to 80 Mbps; customize with ${ClrGrn}${ClrBld}-b${ClrOff} as needed."

printf '%s\n' \
	"* TCP test command with public IP:"
printf '%s\n' \
	"${ClrGrn}${ClrBld}iperf${Version} -i1 -c ${PublicIP} -p 25002${ClrOff}"
printf '\n%s\n' \
	"* UDP test command with public IP:"
printf '%s\n' \
	"${ClrGrn}${ClrBld}iperf${Version} -i1 -c ${PublicIP} -u -p 25002 -b 80M${ClrOff}"

## Continue only if Tailscale is running
if [[ ${Tailscale} != y ]]; then
	exit 1
fi

## Provide Tailscale IPv4 & IPv6 test commands
printf '\n%s\n' \
	"* TCP test command with Tailscale IPv4:"
printf '%s\n' \
	"${ClrGrn}${ClrBld}iperf${Version} -i1 -c ${TailscaleIP4} -p 25002${ClrOff}"

printf '\n%s\n' \
	"* UDP test command with Tailscale IPv4:"
printf '%s\n' \
	"${ClrGrn}${ClrBld}iperf${Version} -i1 -c ${TailscaleIP4} -u -p 25002 -b 80M${ClrOff}"

printf '\n%s\n' \
	"* TCP test command with Tailscale IPv6:"
printf '%s\n' \
	"${ClrGrn}${ClrBld}iperf${Version} -i1 -c ${TailscaleIP6} -p 25002${ClrOff}"

printf '\n%s\n' \
	"* UDP test command with Tailscale IPv6:"
printf '%s\n' \
	"${ClrGrn}${ClrBld}iperf${Version} -i1 -c ${TailscaleIP6} -u -p 25002 -b 80M${ClrOff}"
